### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by janl** [hoodiehq/discussion#38]
We need a single document that tracks Hoodie’s roadmap. This is it. @janl is responsible.

The version numbers here correspond to the entire Hoodie system releases. Individual components have their own version numbers.

Hoodie’s current version: 0.2.0.

The Roadmap:

#### Release 0.1.0 Document Global Shares:
- [x] Document Global Shares hoodiehq/documentation/issues/4

#### Release 0.2.0 New Hoodie Admin Dashboard:
- [x] New Pocket: Document how to do custom views in Pocket hoodiehq/documentation/issues/5 (depends on hoodiehq/pocket/issues/45)

#### Release 0.3.0 Continuous Integration & Release Train (@boennemann):
- [x] Comprehensive Release train process hoodiehq/discussion/issues/46
- [x] Comprehensive Continuous Integration hoodiehq/hoodie-integration-test/issues/1 hoodiehq/hoodie-integration-test/issues/3

#### Release 0.4.0 User Plugin (@caolan):
hoodie-plugin-users:
- [x] Refactor hoodie-plugin-users hoodiehq/hoodie-plugin-users/issues/24
- [ ] Add invite only mode hoodiehq/hoodie-plugin-users/issues/15
- [ ] Make automatic account confirmation optional hoodiehq/hoodie-plugin-users/issues/14
- [ ] Implement proper password reset hoodiehq/hoodie-plugin-users/issues/22
- [ ] Document user registration flow hoodiehq/documentation/issues/7
- [ ] Refactor Account API ~~hoodiehq/hoodie.js/issues/330~~ hoodiehq/discussion/issues/47
- [x] New Pocket UI

#### Release 0.5.0 Payments (@janl) _to be removed?_:
- [ ] Create hoodie-plugin-payments-stripe
- [ ] Document hoodie-plugin-payments-stripe

#### Release 0.6.0 Security (@caolan):
- [ ] Document Hoodie security hoodiehq/documentation/issues/8

#### Release 0.7.0 try.hood.ie (@janl):
- [ ] Create docker wrapper for try.hood.ie https://github.com/caolan/docker-hoodie
- [ ] Build try.hood.ie hoodiehq/try.hood.ie
- [ ] Document docker setup hoodiehq/documentation/issues/10
- [ ] Document try.hood.ie hoodiehq/documentation/issues/9

#### Release 0.8.0 App / Plugin Templates (@zoepage):
- [ ] Update hoodie-plugin-template hoodiehq/documentation/issues/12
- [ ] Document my-first-hoodie hoodiehq/documentation/issues/11

#### Release 0.9.0 PouchDB (@gr2m): 
- [ ] Refactor hoodie.js: externalize state for simpler testing & PouchDB compatibility hoodiehq/hoodie.js/issues/343
- [ ] Make hoodie.js promises standard-complient for PouchDB compatibility hoodiehq/hoodie.js/issues/311
- [ ] Migrate to PouchDB hoodiehq/hoodie.js/issues/8

#### Release 0.10.0 *.hood.ie relaunch (@ffffux):
- [x] Website relaunch
- [x] Documentation launch
- [ ] 4 screencasts
- [ ] Document deployments
- [ ] Press kits

#### Release 0.11.0 Release Communications (@ffffux):
- [ ] Document contributor onboarding
- [ ] Blog posts
  - 7 posts: Team Intro
  - 5 posts: Philosophy: Introducing Hoodie's Core Values
  - 4 posts: Concepts
  - 6 posts: Hoodie for Absolute Beginners
  - 1 post: The Hoodie Story
- [ ] Merchandising
- [ ] Events / Launch Party
- [ ] Set up, create content + contact people for Media Campaign
- [ ] Press Articles

* * *

#### Release 1.0.0:
- [ ] Ship It

**Comment by almereyda** [comment]
Once it ever gets to the launch party, I'd love to donate [a massive dub set](https://soundcloud.com/circushomonovus/almereyda-pirate-dub) for the last women ~~standing~~dancing.

**Comment by Charlotteis** [comment]
I'm wondering if this needs updating/changing? Thoughts?
